server.port=${PORT:8080}
spring.application.name=servidorlocal
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.jpa.database-platform=${DB_DIALECT}

server.tomcat.max-http-form-post-size=2MB

# Configuracao de servidor do Email - Gmail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=4lf4s4ntos@gmail.com
spring.mail.password=cxdodwjlghecvkdn

# Configuracao avancadas da seguranca exigida pelo - Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:12345678901234567890123456789012}

